FROM python:3.11.8-slim

# Chuyển vào thư mục /app trong container
WORKDIR /app

# Copy toàn bộ code vào trong container
COPY . .

# Cài đặt các thư viện cần thiết
RUN pip install pandas sqlalchemy psycopg2-binary sentence-transformers streamlit ollama python-dotenv

# Mở cổng 8555 cho Streamlit
EXPOSE 8555

# Lệnh khởi chạy Web App trên cổng 8555
CMD ["streamlit", "run", "app.py", "--server.port=8555", "--server.address=0.0.0.0"]